version: '3.8'
services:
  app:
    build: .
    ports:
      - "8081:8081"
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://bank-post.cza28kas6dwv.ap-southeast-1.rds.amazonaws.com:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456789
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"