spring:
  datasource:
    url: jdbc:postgresql://bank-post.cza28kas6dwv.ap-southeast-1.rds.amazonaws.com:5432/postgres
    username: postgres
    password: 123456789
    driver-class-name: org.postgresql.Driver
  redis:
    host: localhost
    port: 6379
    password:
    database: 1

mybatis:
  type-aliases-package: com.kl.bankmaster.model
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8080
  ssl:
    protocol: TLS
    key-store: classpath:testserver.keystore
    key-password: 123456
    key-store-type: JKS
