spring:
  datasource:
    url: jdbc:postgresql://bank-post.cza28kas6dwv.ap-southeast-1.rds.amazonaws.com:5432/postgres
    username: postgres
    password: 123456789
    driver-class-name: org.postgresql.Driver
  redis:
    host: localhost
    port: 6379
    password:
    database: 1
  mail:
    host: smtp.163.com
    port: 465
    username: 18090664363@163.com
    password: ZYGCNUGYIOQTJAIN
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          starttls:
            enable: true

mybatis:
  type-aliases-package: com.kl.bankmaster.model
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8080
  httpPort: 8081
  ssl:
    protocol: TLS
    key-store: classpath:testserver.keystore
    key-password: 123456
    key-store-type: JKS

encryption:
  secretKey: vt3IHkeUwVOTedGTS6XnRmatQSQjYIXd0Rj7hggcV60=




