spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  redis:
    host: localhost
    port: 6379
    password:
    database: 1

mybatis:
  type-aliases-package: com.kl.bankmaster.model

server:
  port: 8080
